mongo:
  image: mongo
  expose:
    - "27017"
  ports:
    - "27017:27017"

redis:
  image: redis
  expose:
    - "6379"
  ports:
    - "6379:6379"

mongocli:
  image: mongo
  links:
    - mongo
  command: echo 'ok'
